secret:
  encoder:
    secret: ${PASSWORD_ENCODER_SECRET}
    salt-length: 16
    iteration: 1234
jwt:
  token:
    header: X-AIREVIEW-AUTH
    issuer: aireview
    client-secret: ${JWT_TOKEN_SECRET}
    expiry-seconds: 600
    refresh-token-expiry-seconds: 864000


