spring:
  messages:
    basename: errors
---
spring:
  config:
    activate:
      on-profile: local, dev
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 8
      minimum-idle: 8
      connection-timeout: 2000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    validateMigrationNaming: true
---
spring:
  config:
    activate:
      on-profile: prod
