spring:
  profiles:
    include: domain, oauth
---
spring:
  config:
    activate:
      on-profile: local, dev
  batch:
    job:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
