name: Java CI with Gradle(api)

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew :app-api:build

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and Push Docker Image
        with:
          image: i960107/aireview
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ssh and start new image
        run: |
          echo "$SSH_PEM_KEY" > $HOME/key.pem
          chmod 400 $HOME/key.pem
          ssh -i $HOME/key.pem -o StrictHostKeyChecking=no -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} 
          echo "$SERVER_SECRET"
          ~/script.sh
        env:
          SSH_USER: ${{ secrets.USER }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_PEM_KEY: ${{ secrets.KEY }}
          SSH_PORT: ${{ secrets.PORT}}
          SERVER_SECRET: $${secrets.SERVER_SECRET}}
